quarkus.http.port=8084
quarkus.kafka.devservices.image-name=redpandadata/redpanda:v24.1.2

quarkus.mongodb.database=billing

mp.messaging.incoming.invoices.connector=smallrye-rabbitmq

mp.messaging.outgoing.invoices-confirmations.connector=smallrye-kafka

mp.messaging.incoming.invoices-adjust.connector=smallrye-kafka
mp.messaging.incoming.invoices-adjust.auto.offset.reset=earliest